### ISSUE TITLE
AttributeError: type object 'SciTail' has no attribute 'urls'

### ISSUE THREAD

**Issue by lmdsghero** [Helsinki-NLP/HBMP#1]
When i want to replay your code , i meeting a problem : 
             AttributeError: type object 'SciTail' has no attribute 'urls'. @jorgtied

**Comment by aarnetalman** [comment]
Please make sure that you have downloaded the required datasets using the download_data.sh script before running the code. The error is caused by torchtext which tries to load the SciTail dataset.

**Comment by lmdsghero** [comment]
OK,i downloaded the data using the download_data.sh,but it‘s folder name is ".data" that i can't seeing, so ineed i change the folder name?

**Comment by aarnetalman** [comment]
please don’t change the folder name as the code expects to find the datasets in that location. .data is a hidden folder. You can see it by typing ls -a (in Unix/ Linux system).
