### ISSUE TITLE
Could this model run on the newest pytorch version?

### ISSUE THREAD

**Issue by nutshell999** [Helsinki-NLP/HBMP#10]
Hello, my friend! When I run  the model, I found that the version of the dependency which model need is too old , and now we use pytorch 1.8.0+、python 3.7+. So I just want to know  this model could run in the newest pytorch version?   More important , i find a problem that :

RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /tmp/pip-req-build-ufslq_a9/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /tmp/pip-req-build-ufslq_a9/caffe2/serialize/inline_container.cc:132)

and  my environment is:
pytorch(1.8.1)
spacy(3.0.5)
torchtext(0.9.1)
cudatoolkit(cudatoolkit)

What should i do for this problem .  Look forward your early reply!

**Comment by nutshell999** [comment]
![image](https://user-images.githubusercontent.com/57242327/115201793-4bf45680-a128-11eb-97e4-e1c1f6cbb6f0.png)

**Comment by aarnetalman** [comment]
Hi. Thanks for your interest. I have not had time to update the code on Github but I do have a version that runs on a newer version of PyTorch. I will try to get it online sometime soon. I will comment below with a link when done.

**Comment by nutshell999** [comment]
Ok. Thanks！

**Comment by yanyou426** [comment]
Hello, is the newest version uploaded?

**Comment by aarnetalman** [comment]
Unfortunately, I've not had time to maintain this repository. You should be able to make the required changes looking at the error messages and following this migration guide: https://pytorch.org/blog/pytorch-0_4_0-migration-guide/

**Comment by aarnetalman** [comment]
Actually there was a pull request that has the required changes. I've merged the changes but have not tested.
