### ISSUE TITLE
Everytime i runing your code i need re-download the glove.840B.300d.zip

### ISSUE THREAD

**Issue by lmdsghero** [Helsinki-NLP/HBMP#2]
Everytime i runing your code i need re-download the glove.840B.300d.zip：
       I run your code many times but everytime ,it will download the glove.840B.300d.zip.
       I find lines 154 code : “os.path.isfile(pretrained_embedding)” is always Flase , that mabey path proble

**Comment by lmdsghero** [comment]
Ok， i solve this problem  by change the 154 lines code.

**Comment by aarnetalman** [comment]
Unfortunately I'm not able to reproduce this behaviour. Let me look into it.

**Comment by lmdsghero** [comment]
Think you for your help, i have solve this problem. The reason is that my computer memory is not enough before,so run always fails.

**Comment by aarnetalman** [comment]
Ok. I will close this issue then.
