### ISSUE TITLE
Find the error when running the train_hbmp.sh & train.py

### ISSUE THREAD

**Issue by Zeinab-Kouhkan** [Helsinki-NLP/HBMP#6]
Hi, thanks for your contributions.
I have studied your model and I intend to evaluate its results in another language.
After running the following code, I find a RuntimeError in the last line
how to fix this error? please guide me and explain it?

`!/bin/bash /content/drive/My\ Drive/HBMP-master/train_hbmp.sh`

The `device` argument should be set by using `torch.device` or passing a string as an argument. This behavior will be deprecated soon and currently defaults to cpu.
The `device` argument should be set by using `torch.device` or passing a string as an argument. This behavior will be deprecated soon and currently defaults to cpu.
The `device` argument should be set by using `torch.device` or passing a string as an argument. This behavior will be deprecated soon and currently defaults to cpu.
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py:46: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.1 and num_layers=1
  "num_layers={}".format(dropout, num_layers))

Config: ['--epochs', '20', '--batch_size', '64', '--corpus', 'scitail', '--encoder_type', 'HBMP', '--activation', 'leakyrelu', '--optimizer', 'adam', '--word_embedding', 'glove.840B.300d', '--embed_dim', '300', '--fc_dim', '600', '--hidden_dim', '600', '--layers', '1', '--dropout', '0.1', '--learning_rate', '0.0005', '--lr_patience', '1', '--lr_decay', '0.99', '--lr_reduction_factor', '0.2', '--weight_decay', '0', '--early_stopping_patience', '3', '--save_path', 'results', '--seed', '1234']

Namespace(activation='leakyrelu', batch_size=64, cells=2, corpus='scitail', dropout=0.1, early_stopping_patience=3, embed_dim=300, embed_size=22693, encoder_type='HBMP', epochs=20, fc_dim=600, gpu=0, hidden_dim=600, layers=1, learning_rate=0.0005, lower=True, lr_decay=0.99, lr_patience=1, lr_reduction_factor=0.2, optimizer='adam', out_dim=2, resume_snapshot='', save_path='results', seed=1234, weight_decay=0.0, word_embedding='glove.840B.300d')
Model:

NLIModel(
  (sentence_embedding): SentenceEmbedding(
    (word_embedding): Embedding(22693, 300)
    (encoder): HBMP(
      (max_pool): AdaptiveMaxPool1d(output_size=1)
      (rnn1): LSTM(300, 600, dropout=0.1, bidirectional=True)
      (rnn2): LSTM(300, 600, dropout=0.1, bidirectional=True)
      (rnn3): LSTM(300, 600, dropout=0.1, bidirectional=True)
    )
  )
  (classifier): FCClassifier(
    (activation): LeakyReLU(negative_slope=0.01)
    (mlp): Sequential(
      (0): Dropout(p=0.1)
      (1): Linear(in_features=14400, out_features=600, bias=True)
      (2): LeakyReLU(negative_slope=0.01)
      (3): Dropout(p=0.1)
      (4): Linear(in_features=600, out_features=600, bias=True)
      (5): LeakyReLU(negative_slope=0.01)
      (6): Linear(in_features=600, out_features=2, bias=True)
    )
  )
)

Parameters: 28799102

Training started...

Epoch: 01/20 (Learning rate: 0.0005)
Traceback (most recent call last):
  File "train.py", line 393, in <module>
    main()
  File "train.py", line 260, in main
    answer = model(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/HBMP-master/classifier.py", line 57, in forward
    prem = self.sentence_embedding(batch.premise)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/HBMP-master/embeddings.py", line 19, in forward
    sentence = self.word_embedding(input_sentence)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/sparse.py", line 118, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1454, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
**RuntimeError: Expected object of backend CUDA but got backend CPU for argument #3 'index'**

**Comment by aarnetalman** [comment]
Hi. Thanks for using our code. Are you running this on a machine with a GPU? Which version of PyTorch are you using. -Aarne

**Comment by Zeinab-Kouhkan** [comment]
Yes, I am running this on Google Colab and selecting GPU on Jupyter notebook.
PyTorch-0.4.1

**Comment by aarnetalman** [comment]
Could be related to PyTorch version. The code is written using PyTorch 0.3.1. We have not tested with 0.4.

**Comment by Zeinab-Kouhkan** [comment]
Now I have these versions:
Python (3.6.7)
Pytorch (0.3.1)
Numpy (1.14.3)
Torchtext (0.2.1)
SpaCy (2.0.11)
But there is an error:

Traceback (most recent call last):
  File "train.py", line 393, in <module>
    main()
  File "train.py", line 156, in main
    map_location=lambda storage, location: storage.cuda(config.gpu))
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 267, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 420, in _load
    result = unpickler.load()
**AttributeError: Can't get attribute '_rebuild_tensor_v2' on <module 'torch._utils' from '/usr/local/lib/python3.6/dist-packages/torch/_utils.py'>**

**Comment by aarnetalman** [comment]
Could it be that the code cannot locate the pretrained word embeddings. Have you run the download_data.sh script? That should download the word embeddings.

**Comment by Zeinab-Kouhkan** [comment]
Yes, I have.
![1](https://user-images.githubusercontent.com/44530069/50182020-6f722100-0323-11e9-997f-85fab82a0de8.JPG)

**Comment by Zeinab-Kouhkan** [comment]
I tried to solve this issue:
https://github.com/Zeinab-Kouhkan/HBMP

**Comment by Zeinab-Kouhkan** [comment]
I tried to solve this issue:
https://github.com/Zeinab-Kouhkan/HBMP

**Comment by aarnetalman** [comment]
Hi, Unfortunately I don't have resources or time to verify and fix the issue. Let me know if you find a fix.
Aarne

**Comment by aarnetalman** [comment]
Closing this for now. Let me know if you still experience the issue.
